config/routes.rb
Rails.application.routes.draw do

  root 'events#index'

  devise_for :users

  resources :users, only: [:show] do
    resources :avatars, only: [:create]
  end

  resources :events do
    resources :charges
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/attendance.rb
class Attendance < ApplicationRecord

  belongs_to :user
  belongs_to :event

  after_create :new_attendee

  def new_attendee
   AdminMailer.new_attendee(self).deliver_now
  end

end

app/models/event.rb
class Event < ApplicationRecord

  has_one_attached :picture

  belongs_to :user #admin, class_name: "User"

  has_many :attendances
  has_many :users, through: :attendances

  validates :user_id, presence: true

  #validates :start_date, presence: true
  #validate :cannot_change_the_past

  #validates :duration, presence: true
  #validate :multiple_of_5

  validates :title, presence: true, length: {in: 5..140}

  validates :description, presence: true, length: {in: 20..1000}

  #validates :price, presence: true, inclusion: 1..1000

  validates :location, presence: true
  validate :has_picture

  # Méthode pour vérifier la startdate de l'event,
  # impossible de créer ou modifier un event passé.
  def cannot_change_the_past
	  if start_date.present? && start_date < Date.today
      errors.add(:start_date, "You can't change the past")
	  end
  end

  # Méthode pour vérifier le format de la durée de l'event,
  # impossible de créer sans que ce soit un multiple de 5.
  def multiple_of_5
    if duration == 0 || duration % 5 != 0
  		errors.add(:duration, "it must be a multiple of 5")
  	end
  end

  # Méthode pour calculer la end_date de l'event.
  # def end_date
  # 	start_date + duration * 60
  # end

  def is_coming?(user)
  	if self.attendances.where(user_id: user.id).count > 0
  		return true
  	else
  		return false
  	end
  end

  def has_picture
  	if self.picture.attached? == false
  		errors.add(:picture, "Avec une photo c'est plus sympa !")
  	end
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one_attached :avatar

  has_many :events
  has_many :events, through: :attendances

  after_create :welcome_send

  def welcome_send
   UserMailer.welcome_email(self).deliver_now
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  before_action :configure_devise_parameters, if: :devise_controller?

  def configure_devise_parameters
    devise_parameter_sanitizer.permit(:sign_up) {|u| u.permit(:first_name, :last_name, :email, :password, :password_confirmation)}
    devise_parameter_sanitizer.permit(:account_update) {|u| u.permit(:first_name, :last_name, :email, :password, :password_confirmation)}
  end

end

app/controllers/avatars_controller.rb
class AvatarsController < ApplicationController
  def create
    @user = current_user
    @user.avatar.attach(params[:avatar])
    redirect_to(user_path(@user))
  end
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController

  def new
    @event = Event.find(params[:event_id])
    @amount = @event.price * 100
  end

  def create
    # Amount in cents
    @event = Event.find(params[:event_id])
    @amount = @event.price * 100

    customer = Stripe::Customer.create({
      email: params[:stripeEmail],
      source: params[:stripeToken],
    })

    charge = Stripe::Charge.create({
      customer: customer.id,
      amount: @amount,
      description: 'Rails Stripe customer',
      currency: 'eur',
    })

    @attendance = Attendance.create(stripe_customer_id: params[:stripeToken], user: current_user, event: @event)
      redirect_to @event
      flash[:success] = "Paiement bien reçu. Have fun!"

  rescue Stripe::CardError => e
    flash[:error] = e.message
    redirect_to new_event_charge_path
  end

end

app/controllers/events_controller.rb
class EventsController < ApplicationController

  before_action :authenticate_user!, only: [:new, :create]
	before_action :is_admin, only: [:edit, :update, :destroy]

  def index
    @events = Event.all
  end

  def new
		@event = Event.new
	end

	def create
		@event = Event.new(user: current_user, start_date: params[:start_date], duration: params[:duration], title: params[:title], description: params[:description], price: params[:price], location: params[:location])
		@event.save
		@event.picture.attach(params[:picture])

		if @event.save
			redirect_to event_path(@event)
			flash[:success] = "Your event has been successfully created"
		else
			render 'new'
		end
	end

	def show
		@event = Event.find(params[:id])
	end

	def edit
		@event = Event.find(params[:id])
	end

	def update
		@event = Event.find(params[:id])

		if @event.update(admin: current_user, start_date: params[:start_date], duration: params[:duration], title: params[:title], description: params[:description], price: params[:price], location: params[:location])
			redirect_to event_path
			flash[:success] = "Your event has been successfully edited"
		else
			render :edit
		end
	end

	def destroy
		@event = Event.find(params[:id])
		@event.destroy
		redirect_to root_path
	end

	def is_admin
		@event = Event.find(params[:id])

		if current_user != @event.admin
			flash[:alert] = "Access denied"
			redirect_to event_path
		end

	end

	def has_picture
	   if Event.picture.attached?
		   return true
	   else
		   render 'new'
		   flash[:alert] = "You must upload a picture"
	   end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = current_user
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/avatars_helper.rb
module AvatarsHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/event_helper.rb
module EventHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/avatars/create.html.erb
<h1>Avatars#create</h1>
<p>Find me in app/views/avatars/create.html.erb</p>

app/views/charges/create.html.erb
<h2>Thanks, you paid <strong>$5.00</strong>!</h2>

app/views/charges/new.html.erb
<%= form_tag charges_path do %>
  <article>
    <% if flash[:error].present? %>
      <div id="error_explanation">
        <p><%= flash[:error] %></p>
      </div>
    <% end %>
    <label class="amount">
      <span>Amount: $5.00</span>
    </label>
  </article>

  <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
          data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
          data-description="A month's subscription"
          data-amount="500"
          data-locale="auto"></script>
<% end %>

app/views/events/index.html.erb
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="">

    <title>mutmutbrite</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/4.0/examples/jumbotron/">

    <!-- Bootstrap core CSS -->
    <link href="../../dist/css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="jumbotron.css" rel="stylesheet">
  </head>

  <body>

    <main role="main">

      <!-- Main jumbotron for a primary marketing message or call to action -->
      <div class="jumbotron">
        <div class="container">
          <h1 class="display-4 font-weight-bold">Les meilleurs events, le tien aussi</h1>
          <h2 class="display-5">Ton event sera vu par des milliers de gens, qui en inviteront des milliers d'autres, et il fera les gros titres de la gazette de ton village.</h2>
          <p>Tu feras le buzz, ce qui t'apportera une célébrité relative durant quelques semaines. Tu prendras la grosse tête un peu trop vite, et tu commenceras à consommer des substances illicites pour oublier le fait que tu tombes peu à peu dans l'oubli. Bref, tu mourras comme une rockstar. Sauf que la gazette du village n'en parlera pas elle non plus.</p>
          <p><%= link_to "Crée ton premier événement", new_event_path, class:"btn btn-warning btn-lg", role:"button" %></p>
        </div>
      </div>

      <div class="container">
      <div class="row">
        <% @events.each do |event| %>
          <div class="col-sm" style="padding: 15px">
        <div class="card" style="width: 32rem;">
          <%= image_tag event.picture, alt: 'Event', style:'object-fit: cover; height: 120px; width: 100%; display: block;' %>
          <div class="card-body">
            <h4 class="card-title mb-3"> <%= event.title %> </h4>
            <h5 class="card-subtitle mb-2 text-muted">🤠 <%= event.user.first_name %> </h5>
            <h5 class="card-subtitle mb-2 text-muted">📍 <%= event.location %> </h5>
            <h5 class="card-subtitle mb-2 text-muted">🗓 <%= event.start_date %> </h5>
            <h5 class="card-subtitle mb-2 text-muted">✅ <%= event.attendances.count %> participants </h5>
            <p class="card-text mt-3">  <%= event.description %> </p>
            <p> <%= link_to "Voir", event_path(id: event.id), class:"btn btn-primary btn", role:"button" %> </p>
          </div>
        </div>
        </div>
        <% end %>
      </div>
      </div>

    </main>

    <footer class="container">
      <p>&copy; mutmutbrite 2019</p>
    </footer>

    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script>window.jQuery || document.write('<script src="../../assets/js/vendor/jquery-slim.min.js"><\/script>')</script>
    <script src="../../assets/js/vendor/popper.min.js"></script>
    <script src="../../dist/js/bootstrap.min.js"></script>
  </body>
</html>

app/views/events/new.html.erb
<% if @event.errors.any? %>
<div class="alert alert-danger" role="alert">
 <p>Oups, il manque quelque chose...</p>
 <ul>
   <% @event.errors.full_messages.each do |message| %>
   <li><%= message %></li>
   <% end %>
 </ul>
</div>
<% end %>

<div class="text-dark">
  <h3 class="text-center mt-3 mb-4">Crée ton événement</h3>

  <!-- Zone du formulaire -->
  <%= form_tag events_path, multipart: true, class: "col col-4 mx-auto" do %>

  <div class="field form-group">
  <b><%= label_tag 'Titre' %>
  <%= text_field_tag 'title', @event.title, class: "form-control"  %>
  <small id="emailHelp" class="form-text text-muted mb-3">En 5 à 140 caractères :)</small>
  </div>

  <div class="field form-group">
  <b><%= label_tag "Date de l'event" %></b><br>
  <%= date_select("date", "written_on", start_year: 2019, class:"form-control") %> à <%= time_select("article", "sunrise")%><br>
  </div>

  <div class="field form-group">
  <b><%= label_tag 'Durée' %></b><br>
  <%=  select_minute(30 , minute_step: 5) %> minutes
  </div>

  <div class="field form-group">
  <b><%= label_tag 'Description' %></b>
  <%= text_area_tag 'description', @event.description, class: "form-control"  %>
  <small id="emailHelp" class="form-text text-muted mb-3">En 20 à 1000 caractères</small>
  </div>

  <div class="field form-group">
  <b><%= label_tag 'Prix' %></b>
  <%= text_field_tag 'price', @event.price, class: "form-control mb-3", placeholder: "€" %>
  </div>

  <div class="field form-group">
  <b><%= label_tag 'Lieu' %></b>
  <%= text_field_tag 'location', @event.location, class: "form-control mb-3"  %>

  <div class="field form-group">
  <b><%= label_tag 'Jolie image' %></b><br>
  <%= file_field_tag :picture, class: "mb-3" %>
  </div>

  <div class="field form-group">
  <%= submit_tag "Créer l'event", class: "btn btn-primary mb-4 mt-3" %>
  </div>

  <% end %>

</div>

app/views/events/show.html.erb
<div class="container">

<div class="row">

<div class="mt-4 col col-8 mx-auto">

	<%= image_tag @event.picture, alt: 'Ton super event', style:'object-fit: cover; height: 200px; width: 100%; display: block;' %>

<div class="card" >
  <div class="card-body">
    <h4 class="card-title mb-3"> <%= @event.title %> </h4>
    <h5 class="card-subtitle mb-2 text-muted">🤠 <%= @event.user.first_name %> </h5>
    <h5 class="card-subtitle mb-2 text-muted">📍 <%= @event.location %> </h5>
    <h5 class="card-subtitle mb-2 text-muted">🗓 <%= @event.start_date %> </h5>
    <h5 class="card-subtitle mb-2 text-muted">✅ <%= @event.attendances.count %> participants </h5>
    <p class="card-text mt-3">  <%= @event.description %> </p>
  </div>
</div>


	</div>

	<div class="mt-4 col col-4 mx-auto">

	<div class="card border-secondary mb-3 col-4" style="max-width: 20rem;">
  <div class="card-body">
    <h4 class="card-title">C'est ici que tu sors la CB</h4>
    <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>

		<%= form_tag event_charges_path(@event) do %>
		  <article>
		    <% if flash[:error].present? %>
		      <div id="error_explanation">
		        <p><%= flash[:error] %></p>
		      </div>
		    <% end %>
		    <label class="amount">
		      <span><b>Aboule le fric : <%= @event.price %> €</b></span>
		    </label>
		  </article>

		  <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
		          data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
		          data-description="<%= @event.title %>"
		          data-amount= "<%= @event.price * 100 %>"
		          data-locale="auto"></script>
		<% end %>

			<% if current_user %>
				<% if @event.price > 0 %>
					<% unless @event.user == current_user || @event.is_coming?(current_user) %>
						<p><%= link_to "Rejoins l'événement", root_path, class: "btn btn-primary", role: "button" %></p>
					<% end %>

				<% else %>
					<% unless @event.user == current_user || @event.is_coming?(current_user) %>
						<p><%= button_to "Rejoins l'événement", root_path, class:"btn btn-success" %></p>
					<% end %>
				<% end %>
			<% end %>

  </div>

</div>

</div>


</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>mutmutbrite</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link href="https://stackpath.bootstrapcdn.com/bootswatch/4.3.1/pulse/bootstrap.min.css" rel="stylesheet" integrity="sha384-/uQFqO50IaQu2rNJYKPpV7zwsWJtd6V4DGX4wMw1ATz4KPuZEV96qQ2heVAw2kr2" crossorigin="anonymous">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>

  <body>

    <nav class="navbar navbar-expand-lg navbar-white bg-white border-bottom border-primary">
      <%= link_to "mutmutbrite", root_path, class:"navbar-brand text-primary font-weight-bold" %>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="navbarColor03" aria-controls="navbarColor03" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarColor03">
      </div>

      <div>
      <%= link_to "Créer un événement", new_event_path, class:"btn btn-warning", role:"button" %>

      <% if user_signed_in? %>
        <div class="btn-group">
        <button type="button" class="btn btn-secondary border border-primary btn-sm">Bienvenue <%= current_user.first_name %> 🔥</button>
        <button type="button" class="btn btn-primary dropdown-toggle dropdown-toggle-split" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <span class="sr-only">Toggle Dropdown</span>
        </button>
        <div class="dropdown-menu">
          <%= link_to "Ton profil", user_path(id: current_user.id), class:"dropdown-item" %>
          <div class="dropdown-divider"></div>
          <%= link_to "Déconnexion", destroy_user_session_path, method: :delete, class:"dropdown-item" %>
        </div>
        </div>
        <% else %>
        <%= link_to "Inscription", new_user_registration_path, class:"btn btn-secondary btn-sm", role:"button" %>
        <%= link_to "Connexion", new_user_session_path, class:"btn btn-primary btn-sm", role:"button" %>
      <% end %>
      </div>

      </nav>

      <% if flash[:danger] %>
        <div class="alert alert-danger" role="alert">
          <%= flash[:danger] %>
        </div>
      <% end %>

      <% if flash[:success] %>
        <div class="alert alert-success" role="alert">
          <%= flash[:success] %>
        </div>
      <% end %>



    <%= yield %>

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>
</html>

app/views/layouts/charges.html.erb
<!DOCTYPE html>
<html>
  <head></head>
  <body>
    <%= yield %>
  </body>
</html>

app/views/users/show.html.erb
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Profil</title>
  </head>
  <body class="text-center">

    <h1>Page Profil</h1>

    <p>Bienvenue sur la page d'ajout d'un avatar pour le User portant l'id : <%=@user.id%></p>
    <h3>Avatar actuel</h3>
    <% if @user.avatar.attached? %>
      <%= image_tag @user.avatar, alt: 'avatar', style:'object-fit: cover; width: 200px; height: 200px;' %>
    <% else %>
      <%= @user.avatar.attach(io: File.open('app/assets/images/users/default_avatar.jpg'), filename: 'avatar.jpg') %>
      <%= image_tag @user.avatar, alt: 'avatar', style:'object-fit: cover; width: 200px; height: 200px;' %>
    <% end %>

    <h3>Éditer la photo</h3>
    <%= form_tag user_avatars_path(@user), multipart: true do %>
      <%= file_field_tag :avatar, class: "form-group" %>
      <%= submit_tag "Enregistrer", class:"btn btn-primary btn-sm" %>
    <% end %>

    <%= link_to "Éditer mon profil", edit_user_registration_path, class:"btn btn-primary btn-sm", role:"button" %>


  </body>
</html>